name: Sync Help to GH-Pages

on:
  push:
    branches:
      - main
    paths:
      - "resources/help.html"

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: "gh-pages"
          fetch-depth: 0 # Fetch all history

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch main branch
        run: git fetch origin main:main

      - name: Merge main into gh-pages
        run: git merge main --no-edit --allow-unrelated-histories

      - name: Copy help.html to docs/index.html
        run: cp resources/help.html docs/index.html

      - name: Commit changes
        run: |
          git add docs/index.html
          if git diff --staged --quiet; then
            echo "No changes to commit, skipping."
          else
            git commit -m "Sync help.html content to docs/index.html"
            git push origin gh-pages
          fi
