name: CI/CD Pipeline

on:
  push:
    branches:
      - "**" # This will trigger the workflow for pushes to any branch
  pull_request:
    branches:
      - "**" # This will trigger the workflow for pull requests to any branch

jobs:
  build_test_lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # --- Basic setup ---
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # --- Node Section ---
      - run: npm ci

      - name: Build Project
        run: npm run build --if-present

      # --- Linting Section ---
      - run: npm run lint

      # --- Run tests ---
      - name: Run general tests
        run: npm run test

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    # This ensures the release step runs only for pushes to the main branch.
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # --- Basic setup ---
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # --- Node Section ---
      - run: npm ci

      - name: Build Project
        run: npm run build --if-present

      # --- Delete dev dependencies ---
      - name: Prepare release
        run: rm -rf node_modules
      - run: npm ci --production

      # --- Cleanup ---
      - name: Cleanup
        run: rm -rf resources/db.json

      # --- Assemble release ---
      - run: mkdir lowmq-latest
      - run: cp -R resources lowmq-latest
      - run: cp -R lowmq.js lowmq-latest
      - run: cp -R config/pm2.config.cjs lowmq-latest
      - run: cp -R package.json lowmq-latest
      - run: cp -R package-lock.json lowmq-latest
      - run: cp -R node_modules lowmq-latest
      - run: cp -R LICENSE lowmq-latest
      - run: cp -R README.md lowmq-latest

      - run: zip -r lowmq.zip lowmq-latest

      # --- Create release ---
      - name: Get the merge commit message
        id: get_commit_message
        run: |
          commit_message=$(git log --format=%B -n 1 | head -n 1)
          echo "commit_message=${commit_message}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.get_commit_message.outputs.commit_message }}
          files: lowmq.zip
          tag_name: latest
