name: Create Release on merge to main

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    steps:
      # --- Basic setup ---
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # --- Node Section ---
      - run: npm ci

      - name: Build Project
        run: npm run build --if-present

      # --- Delete dev dependencies ---
      - name: Prepare release
        run: rm -rf node_modules
      - run: npm ci --production

      # --- Cleanup ---
      - name: Cleanup
        run: rm -rf resources/db.json

      # --- Assemble release ---
      - run: mkdir lowmq-latest
      - run: cp -R node_modules lowmq-latest
      - run: cp -R resources lowmq-latest
      - run: cp -R lowmq.js lowmq-latest
      - run: cp -R LICENSE lowmq-latest
      - run: cp -R README.md lowmq-latest
      - run: cp -R package.json lowmq-latest
      - run: cp -R package-lock.json lowmq-latest

      - run: zip -r lowmq.zip lowmq-latest

      # --- Create release ---
      - name: Get the merge commit message
        id: get_commit_message
        run: |
          commit_message=$(git log --format=%B -n 1)
          echo "commit_message=${commit_message}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.commit_message }}
          files: lowmq.zip
          tag_name: latest
